name: Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci # Ensure dependency versions match lockfile

      - name: Unit Tests
        run: npm test --watchAll=false # Run once